name = "Corso di Informatica per la quarta"
license = "MIT"
licenselink = "https://github.com/malafronte/doc-info-quarta-23-24/blob/main/LICENSE"
description = "Sito didattico per il corso di informatica degli studenti di quarta dell'Istituto Alessandro Greppi di Monticello Brianza"
homepage = "https://github.com/malafronte/doc-info-quarta-23-24/"
demosite = "https://malafronte.github.io/doc-info-quarta-23-24/"
tags = [
    "archive",
    "blog",
    "bootstrap",
    "dark",
    "dark mode",
    "docs",
    "gallery",
    "landing",
    "multilingual",
    "personal",
    "responsive"
]
features = ["search", "flexible", "modular"]
[author]
name = "Gennaro Malafronte"
homepage = "https://github.com/malafronte/"
