name = "Informatica al Greppi"
license = "MIT"
licenselink = "https://github.com/malafronte/malafronte.github.io/blob/main/LICENSE"
description = "Sito didattico per il corso di informatica degli studenti del triennio dell'Istituto Alessandro Greppi di Monticello Brianza"
homepage = "https://github.com/malafronte/malafronte.github.io/"
demosite = "https://malafronte.github.io/malafronte.github.io/"
tags = [
    "archive",
    "blog",
    "bootstrap",
    "dark",
    "dark mode",
    "docs",
    "gallery",
    "landing",
    "multilingual",
    "personal",
    "responsive"
]
features = ["search", "flexible", "modular"]
[author]
name = "Gennaro Malafronte"
homepage = "https://github.com/malafronte/"
